version: "3.7"

services:
  postgres:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_cadastro
    volumes:
      - postgres-13:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
  mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
        - 1025:1025
        - 8025:8025

volumes:
  postgres-13: